all: concurrency2

concurrency2:
	javac DiningPhilosophers.java
	java DiningPhilosophers

clean:
	rm -f *.pdf *.ps *.dvi *.out *.log *.aux *.bbl *.blg *.pyg *.o *.out *.log *.aux *~ *.class 

.PHONY: all show clean ps pdf showps
